"use client";

import { useActionState } from "react";

import { Button, Card, CardTitle, Notice, Pill } from "@/components/app/ui";
import {
  previewPersonalisedAction,
  type PreviewState,
} from "../actions";

const INITIAL: PreviewState = { error: null, samples: [] };

/**
 * Three real messages, before two hundred of them leave in the gym's name.
 *
 * Not a sample of the template with a name dropped in: these are generated by
 * the same function the sender uses, against the first three members actually
 * queued for this campaign. What the gym is approving here is the style, and
 * you cannot approve a style from a description of it.
 *
 * Generated on demand rather than on page load. It costs a fraction of a cent
 * and a couple of seconds, and a gym opening a sent campaign to check
 * something should not pay either.
 */
export function PersonalisedPreview({ campaignId }: { campaignId: string }) {
  const [state, action, pending] = useActionState(
    previewPersonalisedAction,
    INITIAL,
  );

  return (
    <Card>
      <CardTitle>Written for each member</CardTitle>
      <p className="mt-1 mb-4 text-[0.875rem] leading-relaxed text-stone">
        This campaign writes every message individually. Below are three, for
        the first three members in the queue, made the same way the real ones
        will be. Running it again gives different words, which is the point.
      </p>

      <form action={action}>
        <input type="hidden" name="campaignId" value={campaignId} />
        <Button type="submit" variant="quiet" disabled={pending}>
          {pending
            ? "Writing"
            : state.samples.length > 0
              ? "Show me three more"
              : "Show me three"}
        </Button>
      </form>

      {state.error ? (
        <div className="mt-4">
          <Notice tone="warn">{state.error}</Notice>
        </div>
      ) : null}

      {state.samples.length > 0 ? (
        <div className="mt-5 space-y-4">
          {state.samples.map((sample, index) => (
            <div
              key={`${sample.name}-${index}`}
              className="rounded-[var(--radius-md)] border border-ash p-4"
            >
              <div className="mb-2 flex flex-wrap items-center gap-3">
                <p className="text-[0.9375rem] font-semibold text-ink">
                  {sample.name}
                </p>
                {sample.personalised ? (
                  <Pill tone="teal">written for them</Pill>
                ) : (
                  /* Not hidden. If the model refused or failed, this is the
                     message that would genuinely be sent, and the gym should
                     see that it looks like everyone else's. */
                  <Pill>your template, unchanged</Pill>
                )}
              </div>
              <p className="text-[0.9375rem] leading-relaxed whitespace-pre-wrap text-graphite">
                {sample.body}
              </p>
            </div>
          ))}
        </div>
      ) : null}
    </Card>
  );
}
